### ISSUE TITLE
On latest Beta can't import ui under py3

### ISSUE THREAD

**Issue by chibill** [omz/Pythonista-Issues#224]
`>>> import ui
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/var/containers/Bundle/Application/C7183F55-165D-4D34-91F3-36DEBF1E9833/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/site-packages/ui.py", line 6, in <module>
    import inspect
  File "/var/containers/Bundle/Application/C7183F55-165D-4D34-91F3-36DEBF1E9833/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/inspect.py", line 2351, in <module>
    class _ParameterKind(enum.IntEnum):
AttributeError: module 'enum' has no attribute 'IntEnum'`

**Comment by chibill** [comment]
It should also be noted this is on a fresh install from TestFlight

**Comment by omz** [comment]
Strange. I can't reproduce this.

**Comment by chibill** [comment]
I just figure it out. Some thing weird happened when I synced my old stuff back to pythonista. (I had to uninstall and reinstall to get TestFlight to work) So yeah. This is InVaild....
