### ISSUE TITLE
MarkupSafe fails to import

### ISSUE THREAD

**Issue by Leva7** [omz/Pythonista-Issues#306]
When I try to execute `import markupsafe` in Pythonista or import any other packages that depend on `markupsafe` (e. g. `flask`), I get this error:
```
>>> import markupsafe
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/var/mobile/Containers/Bundle/Application/AAEDE6FB-9359-4422-B647-A16F19214356/Pythonista3.app/Frameworks/PythonistaKit3.framework/pylib/site-packages/markupsafe/__init__.py", line 228, in <module>
    from markupsafe._speedups import escape, escape_silent, soft_unicode
  File "/var/mobile/Containers/Bundle/Application/AAEDE6FB-9359-4422-B647-A16F19214356/Pythonista3.app/Frameworks/PythonistaKit3.framework/pylib/site-packages/markupsafe/_speedups.py", line 7, in <module>
    __bootstrap__()
  File "/var/mobile/Containers/Bundle/Application/AAEDE6FB-9359-4422-B647-A16F19214356/Pythonista3.app/Frameworks/PythonistaKit3.framework/pylib/site-packages/markupsafe/_speedups.py", line 6, in __bootstrap__
    imp.load_dynamic(__name__,__file__)
TypeError: 'NoneType' object is not callable
```

It seems like the `_speedups.py` file calls a function that's not present in Python 3.5, judging by the docs. How to get around this issue?

Related to #148

**Comment by omz** [comment]
Can you please test this in the latest version from the App Store (i.e. 3.1)? I cannot reproduce this here, and from the paths in your traceback, it looks very much like you're using an older version.
