### ISSUE TITLE
numpy Import error in Py3.5

### ISSUE THREAD

**Issue by deets** [omz/Pythonista-Issues#407]
iOS 11.0, Pythonista 3.1

>>> import numpy
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/var/containers/Bundle/Application/8143F367-F4F3-4098-8B9E-BF143B8CB883/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/site-packages/numpy/__init__.py", line 171, in <module>
    from . import random
  File "/var/containers/Bundle/Application/8143F367-F4F3-4098-8B9E-BF143B8CB883/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/site-packages/numpy/random/__init__.py", line 103, in <module>
    ranf = random = sample = random_sample
NameError: name 'random_sample' is not defined

**Comment by dgelessus** [comment]
Can you try force-quitting Pythonista and see if the problem still happens?

Sometimes problems like this happen when a script is stopped while it's importing a module. When that happens, the module is not completely imported yet, but Python has already cached it as imported (in `sys.modules`). When you run the script again, Python reuses the cached incomplete module, and then you sometimes get errors about missing names.

The fix for this is to restart the Python process, so the module cache is cleared. In Pythonista, Python runs in the same process as the app itself, so you need to restart the entire app to restart Python.

**Comment by deets** [comment]
Hah. That did it. Sorry for not trying myself first.

**Comment by dgelessus** [comment]
No worries :) The problem is not very obvious. I didn't figure this out myself either, I just remembered this type of error from a thread on the forum.
