### ISSUE TITLE
import re throws exception on startup for latest release

### ISSUE THREAD

**Issue by eddo888** [omz/Pythonista-Issues#506]
Traceback (most recent call last):
  File "/var/containers/Bundle/Application/448B43AC-A8DC-4951-AAF3-30C6583126F2/Pythonista3.app/Frameworks/Py3Kit.framework/pykit_startup.py", line 51, in <module>
    main()
  File "/var/containers/Bundle/Application/448B43AC-A8DC-4951-AAF3-30C6583126F2/Pythonista3.app/Frameworks/Py3Kit.framework/pykit_startup.py", line 47, in main
    import importcompletion
  File "/var/containers/Bundle/Application/448B43AC-A8DC-4951-AAF3-30C6583126F2/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/importcompletion.py", line 26, in <module>
    import imp
  File "/var/containers/Bundle/Application/448B43AC-A8DC-4951-AAF3-30C6583126F2/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/imp.py", line 28, in <module>
    import tokenize
  File "/var/containers/Bundle/Application/448B43AC-A8DC-4951-AAF3-30C6583126F2/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/tokenize.py", line 34, in <module>
    import re
  File "/var/containers/Bundle/Application/448B43AC-A8DC-4951-AAF3-30C6583126F2/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/re.py", line 143, in <module>
    class RegexFlag(enum.IntFlag):
AttributeError: module 'enum' has no attribute 'IntFlag'

**Comment by mikaelho** [comment]
This is because enum is now included. You probably have an old enum package in your site-packages. Remove it and ”all will be well”.

**Comment by zrzka** [comment]
@eddo888 was this solved by @mikaelho recommendation?

**Comment by eddo888** [comment]
yup, reinstalled from scratch and all is well
please close this ticket
