### ISSUE TITLE
Method pen() in turtle module doesn't work

### ISSUE THREAD

**Issue by valdemar1977** [omz/Pythonista-Issues#508]
Hello!
Please try this one:
`from turtle import *`
`pen(fillcolor="black", pencolor="red", pensize=10)`
`penstate=pen()`
In my case has an error:
`Traceback (most recent call last):`
`File "<string>", line 1, in <module>`
`File "/var/containers/Bundle/Application/9D07BD4B-E07D-4F71-A023-DC2C01FD095F/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/site-packages/turtle.py", line 1203, in pen`
    `pen.update(pen_dict)`
`NameError: name 'pen_dict' is not defined`

**Comment by zrzka** [comment]
Confirmed. There's a typo - arg name is `pendict`, but there's `pen_dict` in code in the `turtle` module (line 1203).

**Comment by valdemar1977** [comment]
Any chance to edit locked file?

**Comment by omz** [comment]
@valdemar1977 You cannot edit standard library modules directly, but you could create a modified copy in site-packages (under Python Modules), and it would take precedence over the built-in module when you `import turtle`.

**Comment by cclauss** [comment]
```python
from turtle import *
pen(fillcolor="black", pencolor="red", pensize=10)
pen_dict = pendict  # does this complete hack work?!?
penstate=pen()
```

**Comment by dgelessus** [comment]
@cclauss No, because of the star import. You need to set the `pen_dict` attribute of the `turtle` module, so that the `turtle` functions see it as a global variable. This should work:

```python
import turtle
turtle.pen_dict = turtle.pendict
from turtle import *
pen(fillcolor="black", pencolor="red", pensize=10)
penstate=pen()
```

**Comment by PatoNegro** [comment]
I found the same bug this week and posted a detailed comment on the Pythonista forum: 
https://forum.omz-software.com/topic/5030/bug-turtle-py
