### ISSUE TITLE
Numpy import is failing

### ISSUE THREAD

**Issue by paultopia** [omz/Pythonista-Issues#557]
**System Information**

* Pythonista 3.2 (320000), Default interpreter 3.6.1
* iOS 11.4.1, model iPad6,8, resolution (portrait) 2048.0 x 2732.0 @ 2.0

From console, a simple `import numpy` throws with the following error:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/var/containers/Bundle/Application/DED42F0D-6A64-484A-80E9-CA2529B9A038/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/site-packages/numpy/__init__.py", line 171, in <module>
    from . import random
  File "/var/containers/Bundle/Application/DED42F0D-6A64-484A-80E9-CA2529B9A038/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/site-packages/numpy/random/__init__.py", line 103, in <module>
    ranf = random = sample = random_sample
NameError: name 'random_sample' is not defined
```

**Comment by dgelessus** [comment]
Can you try restarting Pythonista (i. e. remove it from the app switcher, then reopen)? This sort of issue often happens when you stop a script while it was importing numpy, which can lead to Python caching a half-loaded numpy module.

**Comment by paultopia** [comment]
aah, indeed that seems to have taken care of it!  thanks!
