### ISSUE TITLE
broken KeyError crashes Pythonista

### ISSUE THREAD

**Issue by bogdan-coanda** [omz/Pythonista-Issues#559]
basically run this:

class Test (object):
	def __repr__(self):
		return 42 # bad, bad code, but should not crash the software… 
set().remove(Test())

I wanted a prettier message for the KeyError I was getting in my script, so I wrote a __repr__ that by accident raised another exception, thus crashing Pythonista.

**Comment by cclauss** [comment]
Works as expected.  You should get the same results on any Python implementation.  The last line creates an empty set and then attempts to remove something from it.  Given that the set is empty, throwing a KeyError is expected behavior.

**Comment by cclauss** [comment]
I am unable to replicate on
```
Pythonista version 3.2 (320000) running Python 3.6.1 on iOS 11.4.1 on a 64-bit iPhone9,3 with a screen size of (320 x 568) * 2
```

**Comment by dgelessus** [comment]
@cclauss What output do you get when you run OP's code? (It needs to be run from a script by the way, not by typing it into the console.)

**Comment by cclauss** [comment]
Traceback (most recent call last):
  File "/private/var/mobile/Containers/Shared/AppGroup/<removed>/Pythonista3/Documents/crasher.py", line 5, in <module>
    set().remove(Test())
KeyError: <__main__.Test object at 0x10b0c8470>

**Comment by dgelessus** [comment]
That's very strange - your output doesn't indicate that there's any issue with the object's repr. When I run the same code on my Mac (Python 3.6.4), the exception looks like `KeyError: <unprintable KeyError object>`.

I'm still using iOS 10.3.3, so maybe it's an iOS version difference? Seems very unlikely though. (By the way, for me the code crashes Pythonista regardless of whether I use Python 2 or 3.)

**Comment by cclauss** [comment]
Also can __not__ replicate on my iPad:
```
Traceback (most recent call last):
  File "/private/var/mobile/Containers/Shared/AppGroup/C2DC6C38-3D98-4394-B761-B6CA01482067/Pythonista3/Documents/crasher.py", line 6, in <module>
    set().remove(Test())
KeyError: <__main__.Test object at 0x108a184e0>


Pythonista version 3.2 (320000) running Python 3.6.1 on iOS 11.4.1 on a 64-bit iPad5,4 with a screen size of (1024 x 768) * 2
```

**Comment by cclauss** [comment]
What?!?  You are not running Python 3.7 on your Mac?

**Comment by idchlife** [comment]
@cclauss it's pretty common case. I run 3.6.4 on my mac too, don't see the problem

**Comment by bogdan-coanda** [comment]
@dgelessus is right: creating a new .py file in Pythonista and running the code from it leads to the Pythonista app hard-crashing on both my iPad (Pro 2, 64bit, iOS 11.4.1, Pythonista 3200000, Python 3.6.1) and my iPhone (8, iOS 11.4, same Pythonista) and it's because the __repr__ throws another exception when it is called for the text to be displayed in the little pink window, and the user code isn't try/catched probably.
