### ISSUE TITLE
Crypto export issue in python 3

### ISSUE THREAD

**Issue by scj643** [omz/Pythonista-Issues#56]
If you try to export an RSA public key with the type of 'OpenSSH'

```
pub.exportKey('OpenSSH')
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/var/mobile/Containers/Bundle/Application/12CBA2CD-EA6B-42E3-9F4B-087378FFE238/Pythonista3.app/Frameworks/PythonistaKit3.framework/pylib/site-packages/Crypto/PublicKey/RSA.py", line 352, in exportKey
    keystring = ''.join([ struct.pack(">I",len(kp))+kp for kp in keyparts]) 
  File "/var/mobile/Containers/Bundle/Application/12CBA2CD-EA6B-42E3-9F4B-087378FFE238/Pythonista3.app/Frameworks/PythonistaKit3.framework/pylib/site-packages/Crypto/PublicKey/RSA.py", line 352, in <listcomp>
    keystring = ''.join([ struct.pack(">I",len(kp))+kp for kp in keyparts]) 
TypeError: can't concat bytes to str
```

**Comment by controversial** [comment]
Do you see this issue on a desktop computer?

**Comment by scj643** [comment]
Ok it's an issue with them and python 3
