### ISSUE TITLE
fatal error on ssl transport

### ISSUE THREAD

**Issue by yjqiang** [omz/Pythonista-Issues#571]
Fatal error on SSL transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x114c80a58>
transport: <_SelectorSocketTransport fd=134 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/private/var/mobile/Containers/Shared/AppGroup/383B28C1-6DCF-40D8-AB53-B5F7548B7F79/Pythonista3/Documents/site-packages-3/aiohttp/client.py", line 391, in _request
    await resp.start(conn)
  File "/private/var/mobile/Containers/Shared/AppGroup/383B28C1-6DCF-40D8-AB53-B5F7548B7F79/Pythonista3/Documents/site-packages-3/aiohttp/client_reqrep.py", line 757, in start
    message, payload = await self._protocol.read()
  File "/private/var/mobile/Containers/Shared/AppGroup/383B28C1-6DCF-40D8-AB53-B5F7548B7F79/Pythonista3/Documents/site-packages-3/aiohttp/streams.py", line 543, in read
    await self._waiter
  File "/var/containers/Bundle/Application/84DF3BDF-B442-41B6-93B3-AB45EDA9E5FC/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/asyncio/futures.py", line 332, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/var/containers/Bundle/Application/84DF3BDF-B442-41B6-93B3-AB45EDA9E5FC/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/asyncio/tasks.py", line 245, in _wakeup
    future.result()
  File "/var/containers/Bundle/Application/84DF3BDF-B442-41B6-93B3-AB45EDA9E5FC/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/asyncio/futures.py", line 237, in result
    raise CancelledError
concurrent.futures._base.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/containers/Bundle/Application/84DF3BDF-B442-41B6-93B3-AB45EDA9E5FC/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/asyncio/sslproto.py", line 640, in _process_write_backlog
    ssldata = self._sslpipe.shutdown(self._finalize)
  File "/var/containers/Bundle/Application/84DF3BDF-B442-41B6-93B3-AB45EDA9E5FC/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/asyncio/sslproto.py", line 156, in shutdown
    ssldata, appdata = self.feed_ssldata(b'')
  File "/var/containers/Bundle/Application/84DF3BDF-B442-41B6-93B3-AB45EDA9E5FC/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/asyncio/sslproto.py", line 220, in feed_ssldata
    self._sslobj.unwrap()
  File "/var/containers/Bundle/Application/84DF3BDF-B442-41B6-93B3-AB45EDA9E5FC/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/ssl.py", line 692, in unwrap
    return self._sslobj.shutdown()
ssl.SSLError: [SSL] called a function you should not call (_ssl.c:2299)

**Comment by yjqiang** [comment]
pythonista 320000 python 3.6.1 aiohttp 3.4.4

**Comment by cclauss** [comment]
Please provide a minimal code snippet that generates this error message.

**Comment by yjqiang** [comment]
https://github.com/omz/Pythonista-Issues/files/2536658/bug.for.pyista.zip

**Comment by jsbain** [comment]
This is not a pythonista bug..

**Comment by yjqiang** [comment]
… Is it a feature again? I can't catch this exception. So I think it is not my fault, too.

**Comment by yjqiang** [comment]
@jsbain https://github.com/aio-libs/aiohttp/issues/3393   Maybe it should have been fixed in python 3.7.1? If I had free time, I would test this on my computer. Right now, I think I should just let it open.
