### ISSUE TITLE
Bug: ctypes.macholib no longer available

### ISSUE THREAD

**Issue by zacbir** [omz/Pythonista-Issues#604]
This is functionality that used to work in previous versions.

**System Information**

* Pythonista 3.2 (320000), Default interpreter 3.6.1
* iOS 12.1.4, model iPhone11,8, resolution (portrait) 750.0 x 1624.0 @ 2.0

>>> from ctypes import util
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/var/containers/Bundle/Application/9673C2ED-EDFD-421C-A652-8B535FAA2058/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/ctypes/util.py", line 72, in <module>
    from ctypes.macholib.dyld import dyld_find as _dyld_find
ModuleNotFoundError: No module named 'ctypes.macholib'

**Comment by dgelessus** [comment]
Duplicate of #311 I believe.

**Comment by zacbir** [comment]
Sure is. Closing this one.
