### ISSUE TITLE
Raise a less esoteric error when ObjCInstance fails

### ISSUE THREAD

**Issue by controversial** [omz/Pythonista-Issues#80]
When an object can't be converted to an ObjCInstance, a completely esoteric error is raised. Typing `ObjCInstance(object())` in the console raises this error:

```
Exception ignored in: Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/var/containers/Bundle/Application/5C7D507A-A8D8-4B73-8880-C9FEB02C8328/Pythonista3.app/Frameworks/PythonistaKit3.framework/pylib/site-packages/objc_util.py", line 534, in __new__
    objc_instance.retain(restype=c_void_p, argtypes=[])
  File "/var/containers/Bundle/Application/5C7D507A-A8D8-4B73-8880-C9FEB02C8328/Pythonista3.app/Frameworks/PythonistaKit3.framework/pylib/site-packages/objc_util.py", line 796, in __call__
    method_name, kwarg_order = resolve_instance_method(obj, self.name, args, kwargs)
  File "/var/containers/Bundle/Application/5C7D507A-A8D8-4B73-8880-C9FEB02C8328/Pythonista3.app/Frameworks/PythonistaKit3.framework/pylib/site-packages/objc_util.py", line 396, in resolve_instance_method
    meth = ObjCInstanceMethod(obj, method_name, allow_property=possibly_property)
  File "/var/containers/Bundle/Application/5C7D507A-A8D8-4B73-8880-C9FEB02C8328/Pythonista3.app/Frameworks/PythonistaKit3.framework/pylib/site-packages/objc_util.py", line 809, in __init__
    objc_class = object_getClass(obj.ptr)
ctypes.ArgumentError: argument 1: <class 'TypeError'>: wrong type
```

It'd be nice if this was friendlier

**Comment by zrzka** [comment]
Currently, it raises:

```
Traceback (most recent call last):
  File "/private/var/mobile/Containers/Shared/AppGroup/501A97B8-BC3B-489A-8267-5A7C98E16408/Pythonista3/Documents/demo.py", line 4, in <module>
    ObjCInstance(object())
  File "/var/containers/Bundle/Application/B6451803-5685-4931-85ED-4E5E93CB0403/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/site-packages/objc_util.py", line 533, in __new__
    if ptr and not b'NSAutoreleasePool' in class_getName(object_getClass(ptr)):
ctypes.ArgumentError: argument 1: <class 'TypeError'>: wrong type
```

It's shorter and IMHO it's fine, raises `TypeError` with `wrong type`. Going to close this one. If you disagree, please, reopen.
